controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_products:
    path: /get/products
    controller: App\Controller\ProductController::all
    methods: ['GET']

get_product:
    path: /get/product/{id}/{productCode}
    controller: App\Controller\ProductController::one
    methods: ['GET']

create_product:
    path: /create/product
    controller: App\Controller\ProductController::create
    methods: ['POST']

get_categories:
    path: /get/categories
    controller: App\Controller\CategoryController::all
    methods: ['GET']

get_category:
    path: /get/category/{id}
    controller: App\Controller\CategoryController::one
    methods: ['GET']

create_category:
    path: /create/category
    controller: App\Controller\CategoryController::create
    methods: ['POST']
